spring:
  datasource:
    url: jdbc:h2:mem:maindb
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    labels: main
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
